### ISSUE TITLE
The command reported in the README does not work for me

### ISSUE THREAD

**Issue by ftomassetti** [JetBrains/mps-maven-deployer#1]
`sh $ ./gradlew publishToMavenLocal` does not work, `./gradlew publishToMavenLocal` does (I am using Linux)

**Comment by sergej-koscejev** [comment]
I wrote '$' there to mean the command prompt, so what you typed was correct. Since it confused at least one person, I'll try to clarify this.

**Comment by ftomassetti** [comment]
Consider me the prototype of a user easy to confuse :)

**Comment by sergej-koscejev** [comment]
Fixed.
