### ISSUE TITLE
Put artificats on Maven Central

### ISSUE THREAD

**Issue by ftomassetti** [JetBrains/mps-maven-deployer#2]
Wouldn't make sense to put the core artifacts on Maven Central, instead of having everyone reinstalling them locally?

I am thinking about:
- mps-core
- mps-editor
- mps-openapi
- mps-platform
- mps-tool

etc.

**Comment by sergej-koscejev** [comment]
That's definitely the goal, the deployer should go away eventually, but first the creation of artifacts and their deployment needs to be integrated into the MPS build process on teamcity.jetbrains.com.

Also, the internal layout of the artifacts had better be stable - for plain library JARs it's not a problem but the packaging of languages is not yet entirely clear.

**Comment by ftomassetti** [comment]
I understand, thank you for the clarification!
