### ISSUE TITLE
downloadMps task failes

### ISSUE THREAD

**Issue by Nelyo** [JetBrains/mps-maven-deployer#3]
>  ./gradlew publishToMavenLocal -PmpsVersion=3.4.1

>  FAILURE: Build failed with an exception.
> 15:35:42.503 [ERROR] [org.gradle.BuildExceptionReporter]
> 15:35:42.503 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
> 15:35:42.503 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':downloadMps'.
> 15:35:42.503 [ERROR] [org.gradle.BuildExceptionReporter] > org.apache.http.client.ClientProtocolException: Forbidden

What I'm doing wrong?

**Comment by sergej-koscejev** [comment]
Apparently the old version is no longer available for download. Not sure why, maybe @ashatalin knows more. `-PmpsVersion=3.4.4` works fine.
